version: "3"
services:
  node:
    build: "./backend"
    depends_on:
      - db
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/:/home/node/app
    expose:
      - "3800"
    ports:
      - "3800:3800"
    #command: "sh"
    tty: true
    entrypoint: 
      - sh
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: 0.0.0.0
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: karaoke
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /usr/local/mysql
      
# Names our volume
volumes:
  my-db: