version: "3"
services:
  node:
    build: "./backend"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/:/home/node/app
    expose:
      - "8888"
    #command: "sh"
    tty: true
    entrypoint: 
      - sh
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080